/*================================================================================================


    ░██████╗██╗░░░██╗██████╗░██╗░░░██╗██╗██╗░░░██╗███████╗  ████████╗██╗███╗░░░███╗███████╗
    ██╔════╝██║░░░██║██╔══██╗██║░░░██║██║██║░░░██║██╔════╝  ╚══██╔══╝██║████╗░████║██╔════╝
    ╚█████╗░██║░░░██║██████╔╝╚██╗░██╔╝██║╚██╗░██╔╝█████╗░░  ░░░██║░░░██║██╔████╔██║█████╗░░
    ░╚═══██╗██║░░░██║██╔══██╗░╚████╔╝░██║░╚████╔╝░██╔══╝░░  ░░░██║░░░██║██║╚██╔╝██║██╔══╝░░
    ██████╔╝╚██████╔╝██║░░██║░░╚██╔╝░░██║░░╚██╔╝░░███████╗  ░░░██║░░░██║██║░╚═╝░██║███████╗
    ╚═════╝░░╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░░╚═╝░░░╚══════╝  ░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚══════╝


    Emmett & Crownshot's Survive Time Gamemode
    Git: github.com/emmett-white/samp-survive-time
    Discord: https://discord.gg/yGRhys2

    Credits:
        Y-Less - YSI-Includes...
        Incognito - Streamer
        JustMichael - Discord help..
        maddinat0r - MySQL
        IllidanS4 - PawnPlus
        AGraber - pawn-plus-mysql
        urShadow - Pawn.RegEx
        ziggi - Protection
        Southclaws - sa-mp logger
        Emmet_ - New SA-MP callbacks
        oscar-broman - weapon-config | SKY
        kurta999's & IllidanS4 - YSF
        dakyskye - Pawn ENV

    Copyright (©) 2020 | 16th June

================================================================================================*/

stock Auth_PromptLogin(const playerid)
{
    inline dialog_login(id, dialogid, response, listitem, string: inputtext[])
    {
        #pragma unused id, dialogid, listitem


        if (!response)
        {
            return Kick(playerid);
        }


        bcrypt_verify(playerid, "OnPasswordVerify", inputtext, player_Password[playerid]);
    }

    Dialog_ShowCallbackF
    (
        playerid, using inline dialog_login, DIALOG_STYLE_PASSWORD,
        D_TITLE,
        ""SERVER">> %s, "WHITE"please enter your correct password..\n\n\
        "SERVER">> "WHITE"You have max %d/"SERVER"%d "WHITE"attempts!",
        D_CONFIRM, D_CANCEL, PlayerName(playerid), player_LoginAttempts[playerid],
        MAX_LOGIN_ATTEMPTS
    );

    return 1;
}